### ISSUE TITLE
Thank you. Please take a look at my environmental configuration issue.

### ISSUE THREAD

**Issue by DevilCJS89** [Lakshadeep/pre-grasp-approaching#3]
I need to know your environment configuration about this project.
When I try configuring the environment, I encountered some problems.
---------------------------
environments:
------------------------------
python==3.7.16
mushroom-rl==1.10.0
ikfastpy----------https://github.com/andyzeng/ikfastpy
------------------------------
Are there any problems with the environment configuration above?
Thank you.

**Comment by DevilCJS89** [comment]
Package                       Version          Editable project location
----------------------------- ---------------- -----------------------------------------------------------
absl-py                       2.1.0
actionlib                     1.14.0
aiobotocore                   1.2.0
aiodns                        2.0.0
aiofiles                      0.4.0
aiohttp                       3.7.4.post0
aioitertools                  0.7.1
aiosignal                     1.3.1
ale-py                        0.7.5
angles                        1.9.13
antlr4-python3-runtime        4.9.3
aruco_detect                  0.12.0
asteval                       0.9.21
async-timeout                 3.0.1
attrs                         20.1.0
base_local_planner            1.17.3
bezier                        2020.5.19
bondpy                        1.8.6
boto3                         1.17.1
botocore                      1.20.49
brotlipy                      0.7.0
cachetools                    5.3.3
camera-calibration            1.17.0
camera-calibration-parsers    1.12.0
catkin                        0.8.10
cchardet                      2.1.6
certifi                       2022.9.24
cffi                          1.15.1
chardet                       4.0.0
charset-normalizer            2.0.4
click                         7.1.2
cloudpickle                   2.2.1
cmake                         3.29.3
construct                     2.10.61
controller-manager            0.20.0
controller-manager-msgs       0.19.6
coverage                      6.1.2
cryptography                  39.0.1
cv-bridge                     1.16.2
cycler                        0.10.0
Cython                        3.0.10
diagnostic-analysis           1.11.0
diagnostic-common-diagnostics 1.11.0
diagnostic-updater            1.11.0
dm-control                    1.0.13
dm-env                        1.6
dm-tree                       0.1.8
docker-pycreds                0.4.0
dynamic-reconfigure           1.7.3
exceptiongroup                1.2.1
fastapi                       0.68.1
filelock                      3.12.2
flit_core                     3.6.0
fonttools                     4.38.0
frozenlist                    1.3.3
gazebo_plugins                2.9.2
gazebo_ros                    2.9.2
gencpp                        0.7.0
geneus                        3.0.0
genlisp                       0.4.18
genmsg                        0.6.0
gennodejs                     2.0.2
genpy                         0.6.15
gitdb                         4.0.11
GitPython                     3.1.43
glfw                          2.7.0
google-auth                   2.29.0
google-auth-oauthlib          0.4.6
grpcio                        1.62.2
gunicorn                      20.1.0
gym                           0.21.0
gym-notices                   0.0.8
h11                           0.14.0
httptools                     0.1.1
Hydra                         2.5
hydra-core                    1.2.0
idna                          3.4
idna-ssl                      1.1.0
ikfast-pybind                 0.1.2
image-geometry                1.16.2
importlib-metadata            4.13.0
importlib-resources           5.12.0
iniconfig                     2.0.0
interactive-markers           1.12.0
Jinja2                        2.11.3
jmespath                      0.10.0
joblib                        1.3.2
joint-state-publisher         1.15.1
joint-state-publisher-gui     1.15.1
jsonschema                    3.2.0
kiwisolver                    1.3.2
labmaze                       1.0.6
laser_geometry                1.6.7
llvmlite                      0.37.0
lxml                          5.2.2
Markdown                      3.4.4
MarkupSafe                    2.1.5
matplotlib                    3.4.3
message-filters               1.16.0
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
moveit-commander              1.1.13
moveit-core                   1.1.13
moveit-python                 0.4.5
moveit-ros-planning-interface 1.1.13
moveit-ros-visualization      1.1.13
moveit-task-constructor-core  0.1.3
msgpack                       1.0.5
mujoco                        2.3.6
multidict                     4.7.6
nest-asyncio                  1.5.1
numba                         0.51.2
numpy                         1.21.6
numpy-quaternion              2020.9.5.14.42.2
nvsmi                         0.4.2
oauthlib                      3.1.1
omegaconf                     2.3.0
omniisaacgymenvs              2.0.0            /home/cjs/isaacsim/isaac_sim/isaac-marl-mobile-manipulation
opencv-python                 4.9.0.80
osqp                          0.6.2.post5
packaging                     21.0
pandas                        1.3.5
pathtools                     0.1.2
Pillow                        9.3.0
Pint                          0.17
pip                           24.0
pkgutil_resolve_name          1.3.10
platformdirs                  4.0.0
pluggy                        1.2.0
pre-grasp-approaching         0.1.0            /home/cjs/isaacsim/isaac_sim/pre-grasp-approaching
protobuf                      3.20.2
psutil                        5.7.2
pyasn1                        0.5.1
pyasn1-modules                0.3.0
pybullet                      3.2.6
pycares                       3.1.1
pycparser                     2.21
pydantic                      1.9.2
pygame                        2.5.2
pykinematics                  1.0.1
PyOpenGL                      3.1.7
pyOpenSSL                     23.0.0
pyparsing                     3.1.2
pyperclip                     1.8.0
pyproject                     1.3.1
pyqtgraph                     0.12.4
pyrsistent                    0.19.2
PySocks                       1.7.1
pytest                        7.4.4
python-dateutil               2.8.2
python-multipart              0.0.5
python-qt-binding             0.4.4
pytz                          2024.1
PyYAML                        5.4.1
qdldl                         0.1.5.post0
qt-dotgraph                   0.4.2
qt-gui                        0.4.2
qt-gui-cpp                    0.4.2
qt-gui-py-common              0.4.2
ray                           2.7.2
redis                         3.5.3
requests                      2.26.0
requests-oauthlib             1.3.0
resource_retriever            1.12.7
rl-games                      1.5.2
ros_numpy                     0.0.5
rosbag                        1.16.0
rosboost-cfg                  1.15.8
rosclean                      1.15.8
roscreate                     1.15.8
rosgraph                      1.16.0
roslaunch                     1.16.0
roslib                        1.15.8
roslint                       0.12.0
roslz4                        1.16.0
rosmake                       1.15.8
rosmaster                     1.16.0
rosmsg                        1.16.0
rosnode                       1.16.0
rosparam                      1.16.0
rospy                         1.16.0
rospy_message_converter       0.5.9
rosserial_python              0.9.2
rosservice                    1.16.0
rostest                       1.16.0
rostopic                      1.16.0
rosunit                       1.15.8
roswtf                        1.16.0
rqt_action                    0.4.9
rqt_bag                       0.5.1
rqt_bag_plugins               0.5.1
rqt-console                   0.4.12
rqt_dep                       0.4.12
rqt_graph                     0.4.14
rqt_gui                       0.5.3
rqt_gui_py                    0.5.3
rqt-image-view                0.4.17
rqt_launch                    0.4.9
rqt-logger-level              0.4.12
rqt-moveit                    0.5.11
rqt_msg                       0.4.10
rqt-multiplot                 0.0.12
rqt_nav_view                  0.5.7
rqt_plot                      0.4.13
rqt_pose_view                 0.5.11
rqt_publisher                 0.4.10
rqt_py_common                 0.5.3
rqt_py_console                0.4.10
rqt-reconfigure               0.5.5
rqt-robot-dashboard           0.5.8
rqt-robot-monitor             0.5.15
rqt_robot_steering            0.5.12
rqt-runtime-monitor           0.5.10
rqt-rviz                      0.7.0
rqt_service_caller            0.4.10
rqt_shell                     0.4.11
rqt_srv                       0.4.9
rqt-tf-tree                   0.6.4
rqt_top                       0.4.10
rqt_topic                     0.4.13
rqt_web                       0.4.10
rsa                           4.9
rviz                          1.14.20
s3transfer                    0.3.7
scikit-learn                  1.0.2
scipy                         1.7.3
selenium                      3.141.0
sensor-msgs                   1.13.1
sentry-sdk                    1.9.8
setproctitle                  1.3.3
setuptools                    65.6.0
shapely                       2.0.4
six                           1.16.0
smach                         2.5.2
smach-ros                     2.5.2
smclib                        1.8.6
smmap                         5.0.1
srdfdom                       0.6.4
stable-baselines3             1.6.2
starlette                     0.14.2
tensorboard                   2.11.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorboardX                  2.6.2.2
tf                            1.13.2
tf-conversions                1.13.2
tf2-geometry-msgs             0.7.7
tf2-kdl                       0.7.7
tf2-py                        0.7.7
tf2-ros                       0.7.7
tf2-sensor-msgs               0.7.7
threadpoolctl                 3.1.0
toml                          0.10.1
tomli                         2.0.1
topic-tools                   1.16.0
torch                         1.13.1
torchaudio                    0.13.1
torchvision                   0.14.0+cu117
tqdm                          4.66.4
trac_ik_python                1.6.6
turtlebot3_example            1.2.5
turtlebot3_teleop             1.2.5
typing_extensions             4.7.1
urdfdom-py                    0.4.6
urllib3                       1.26.12
uvicorn                       0.12.1
wandb                         0.17.0
watchdog                      0.10.4
watchgod                      0.7
webbot                        0.34
websockets                    9.1
Werkzeug                      2.2.3
wheel                         0.38.4
wincertstore                  0.2
wrapt                         1.10.10
xacro                         1.14.16
yarl                          1.5.1
zipp                          3.10.0

**Comment by Lakshadeep** [comment]
I have Python 3.7.13 and Mushroom-rl 1.7.2. IKfast is not required and can be just commented out.

**Comment by DevilCJS89** [comment]
Great job, thank you very much!
