### ISSUE TITLE
About the assets---task.usd and robotiq_arg2f_85_model.usd

### ISSUE THREAD

**Issue by DevilCJS89** [Lakshadeep/pre-grasp-approaching#5]
28/05/2024 10:17:43 [INFO] ###################################################################################################
28/05/2024 10:17:43 [INFO] Experiment Algorithm: SAC
2024-05-28 02:17:45 [11,619ms] [Warning] [omni.usd] Warning: in _ReportErrors at line 2830 of /buildAgent/work/ca6c508eae419cf8/USD/pxr/usd/usd/stage.cpp -- Cycle detected:
@/home/cjs/isaacsim/isaac_sim/pre-grasp-approaching/isaac_envs/task.usd@,@anon:0x18288aa0@</World/ur5e/robotiq_arg2f_85_model/robotiq_arg2f_85_model>
____________________________________________________________
Another problem is can't open the task.usd. 
The issue occurred after the last asset modification.

**Comment by DevilCJS89** [comment]
![2024-05-28 11-23-33 的屏幕截图](https://github.com/Lakshadeep/pre-grasp-approaching/assets/125138575/0fe2d402-6d83-42a0-a5e7-dc207828f35a)

**Comment by Lakshadeep** [comment]
Thank you for posting the error. I have now made the complete `isaac_envs' (assets folder) available for download at the following link: https://drive.google.com/file/d/1LU8-O9ryiOb-zTFRssUWy8UmM0cG0OJn/view?usp=sharing

Just unzip and copy the contents in the `isaac_envs' folder in the repository.
